name: Deploy Node.js Application to Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.1'

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/mnursing-application/server/dev
          git pull origin dev
          npm install --omit=dev
          if pm2 list | grep -q "mnursing-api-dev"; then
            pm2 reload "mnursing-api-dev"
          else
            pm2 start index.js --name "mnursing-api-dev"
          fi
          pm2 save
          pm2 status
