name: Deploy to VPS

on:
  push:
    branches:
      - main
      - dev
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        KEY: ${{ secrets.VPS_SSH_KEY }}
      with:
        source: "server/"
        target: "/home/your-username/mnursing-application/server/${{ github.ref_name }}"

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        KEY: ${{ secrets.VPS_SSH_KEY }}
      with:
        script: |
          pm2 restart /home/your-username/mnursing-application/server/ecosystem.config.js
