name: Node.js CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm install
        run: |
          npm install

      - name: Stop existing PM2 process
        run: pm2 stop mnursing-dev

      - name: Start PM2 process and Save
        run: |
          pm2 start index.js --name "mnursing-dev" --watch 
          pm2 save

      - name: Restart Nginx
        run: sudo service nginx restart
